import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../../styles/AboutPage.module.css";
import { useEffect, useState } from "react";
import navbarData from "../../components/navBar/navBarData";

const inter = Inter({ subsets: ["latin"] });

export default function About() {
  return (
    <>
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.mainText}>
          {/* <h1>About me</h1> */}
          <h1>Hi there!</h1>
          <br />
          {/* <p>Hi there!</p> */}
          <p>
            Throughout my journey in Republic Polytecnic pursuing the Diploma of
            information technology, I&lsquo;ve been exploring different
            applications of IT and where my interest would be in. By the end of
            year 2, I found that there was something in programming that
            intrigued me.
            <br />
            <br />
            Since then, I&lsquo;ve started to do some self-learning and have
            taken part in 4 projects, one being my final-year-project, second
            during my final-year-project , third during my internship and
            lastly, this website. I love that most of my projects had been a
            challenge to me, for instance, an unknown framework or language and
            I managed to pull through all of them.
          </p>
          <br />
          <p>
            As I continue to grow, I hope to be given opportunities to aid in
            honing my skills and I believe that I would be able to become a
            meaningful asset to your organisation
          </p>
        </div>
      </main>
    </>
  );
}
