import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../../styles/projectsPage.module.css";
import { useEffect, useState } from "react";
// import videoDemo from "../../public/projects/project1/videoDemo.mp4";

import ProjectData from "../../components/portfolio/projectData";
import Project1 from "../../components/portfolio/project1";
import Project2 from "../../components/portfolio/project2";
import Project3 from "../../components/portfolio/project3";

const inter = Inter({ subsets: ["latin"] });
export default function Projects() {
  const projectInfo = [
    {
      name: "YouthxIndustry Web Platform",
      date: "07/04/2022",
    },
    {
      name: "E-commerce Website",
      date: "12/09/2022",
    },
    {
      name: "POS system",
      date: "12/09/2022",
    },
  ];
  const projectInfo1 = [
    {
      name: "YouthxIndustry Web Platform",
      date: "07/04/2022",
      html: `<p>
            Throughout my journey in Republic Polytecnic pursuing the Diploma of
            information technology, I&lsquo;ve been exploring different
            applications of IT and where my interest would be in. By the end of
            year 2, I found that there was something in programming that
            intrigued me. Since then, I&lsquo;ve started to do some
            self-learning and have taken part in 3 projects, one being my
            final-year-project, second during my internship and lastly, this
            website
          </p>`,
    }
  ];
  const [activeProjectIndex, setActiveProjectIndex] = useState(0);
  const [previousProjectIndex, setPreviousProjectIndex] = useState(-1);
  const [test, setTest] = useState(false);

  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.projectSelector}>
          {ProjectData.map((element, index) => {
            // eslint-disable-next-line react/jsx-key
            return (
              <p
                className={styles[`projectSelectorName${index + 1}`]}
                key={index}
              >
                {ProjectData[index].name}
              </p>
            );
          })}
          <p>{activeProjectIndex}</p>
          {ProjectData.map((element, index) => {
            // eslint-disable-next-line react/jsx-key
            return (
              <button
                className={styles[`projectSelectorDate${index + 1}`]}
                key={index}
                onClick={() => {
                  setActiveProjectIndex(index);
                }}
              >
                <span
                  className={styles.projectSelectorDateFront}
                  style={
                    activeProjectIndex === index
                      ? {
                          backgroundColor: "white",
                          color: "black",
                        }
                      : {
                          backgroundColor: "transparent",
                          color: "white",
                        }
                  }
                >
                  {ProjectData[index].date}
                </span>
                <span className={styles.projectSelectorDateLowerBorder}></span>
              </button>
            );
          })}
        </div>
        <Project1
          activeProjectIndex={activeProjectIndex}
          projectData={ProjectData}
        />

        <Project2
          activeProjectIndex={activeProjectIndex}
          projectData={ProjectData}
        />

        <Project3
          activeProjectIndex={activeProjectIndex}
          projectData={ProjectData}
        />
      </main>
    </>
  );
}
