import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../../styles/projectsPage.module.css";
import { useState, useEffect } from "react";

import ProjectData from "../../components/portfolio/projectData";
import Project1 from "../../components/portfolio/project1";
import Project2 from "../../components/portfolio/project2";
import Project3 from "../../components/portfolio/project3";
import Project4 from "../../components/portfolio/project4";
import Project5 from "../../components/portfolio/project5";
import Project6 from "../../components/portfolio/project6";
import Project7 from "../../components/portfolio/project7";

const inter = Inter({ subsets: ["latin"] });
export default function Projects() {
  const maxCycle =
    Math.floor(ProjectData.length / 3) + (ProjectData.length % 3 === 0 ? 0 : 1);

  const [projectCycle, setProjectCycle] = useState(1);
  const [previousProjectIndex, setPreviousProjectIndex] = useState(null);
  const [animating, setAnimating] = useState(false);
  const [activeProjectIndex, setActiveProjectIndex] = useState(
    () => (projectCycle - 1) * 3
  );

  const handleProjectCycleChange = (direction) => {
    setProjectCycle((prevCycle) => {
      let newCycle = direction === "forward" ? prevCycle + 1 : prevCycle - 1;
      if (newCycle < 1) newCycle = 1;
      if (newCycle > maxCycle) newCycle = maxCycle;

      setActiveProjectIndex((newCycle - 1) * 3);

      return newCycle;
    });
  };

  useEffect(() => {
    if (
      previousProjectIndex !== null &&
      previousProjectIndex !== activeProjectIndex
    ) {
      setAnimating(true);
      const timer = setTimeout(() => setAnimating(false), 400); // animation duration
      return () => clearTimeout(timer);
    }
    setPreviousProjectIndex(activeProjectIndex);
  }, [activeProjectIndex]);

  const start = (projectCycle - 1) * 3;
  const visibleProjects = ProjectData.slice(start, start + 3);

  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.projectCycleLeftContainer}>
          <button
            className={styles.projectCycleNavigationButton}
            disabled={projectCycle === 1}
            style={{ opacity: projectCycle === 1 ? 0.5 : 1 }}
            onClick={() => handleProjectCycleChange("backward")}
          >
            <Image
              src="/leftArrow.svg"
              alt="LeftArrow Icon"
              className={styles.projectCycleNavigationButtonIconLeft}
              width={50}
              height={50}
            />
          </button>
        </div>

        <div className={styles.projectCycleRightContainer}>
          <button
            className={styles.projectCycleNavigationButtonRight}
            disabled={projectCycle === maxCycle}
            style={{ opacity: projectCycle === maxCycle ? 0.5 : 1 }}
            onClick={() => handleProjectCycleChange("forward")}
          >
            <Image
              src="/rightArrow.svg"
              alt="RightArrow Icon"
              className={styles.projectCycleNavigationButtonIconRight}
              width={50}
              height={50}
            />
          </button>
        </div>

        <div className={styles.projectSelector}>
          {visibleProjects.map((project, idx) => {
            const realIndex = start + idx;
            const classSuffix = (idx + 1) % 3 === 0 ? 3 : (idx + 1) % 3;

            return (
              <div key={realIndex} style={{ marginBottom: "1rem" }}>
                <p className={styles[`projectSelectorName${classSuffix}`]}>
                  {project.name}
                </p>
                <button
                  className={styles[`projectSelectorDate${classSuffix}`]}
                  onClick={() => setActiveProjectIndex(realIndex)}
                >
                  <span
                    className={styles.projectSelectorDateFront}
                    style={
                      activeProjectIndex === realIndex
                        ? { backgroundColor: "white", color: "black" }
                        : { backgroundColor: "transparent", color: "white" }
                    }
                  >
                    {project.date}
                  </span>
                  <span
                    className={styles.projectSelectorDateLowerBorder}
                  ></span>
                </button>
              </div>
            );
          })}
        </div>

        {/* Conditionally render project components only for active project */}
        {activeProjectIndex === 0 && (
          <Project1
            activeProjectIndex={activeProjectIndex}
            projectData={ProjectData}
          />
        )}
        {activeProjectIndex === 1 && (
          <Project2
            activeProjectIndex={activeProjectIndex}
            projectData={ProjectData}
          />
        )}
        {activeProjectIndex === 2 && (
          <Project3
            activeProjectIndex={activeProjectIndex}
            projectData={ProjectData}
          />
        )}
        {activeProjectIndex === 3 && (
          <Project4
            activeProjectIndex={activeProjectIndex}
            projectData={ProjectData}
          />
        )}
        {activeProjectIndex === 4 && (
          <Project5
            activeProjectIndex={activeProjectIndex}
            projectData={ProjectData}
          />
        )}
        {activeProjectIndex === 5 && (
          <Project6
            activeProjectIndex={activeProjectIndex}
            projectData={ProjectData}
          />
        )}
        {activeProjectIndex === 6 && (
          <Project7
            activeProjectIndex={activeProjectIndex}
            projectData={ProjectData}
          />
        )}
      </main>
    </>
  );
}
